TPL_ITEM.Mission_SoraStone = ItemTpl()
    :name("大空陨石")
    :description({ "来自外太空的陨石", "据说拥有改变气候的力量" })
    :modelAlias("item/FrostcraftCrystal")
    :icon("item/DataCrystal08")
    :dropable(false)
    :pawnable(false)
TPL_ITEM.Mission_SnowCore = ItemTpl()
    :name("雪蓝核心")
    :description({ "雪地生灵的核心", "蕴含雪地的能量" })
    :modelAlias("item/FrostShard")
    :icon("item/MiscGemAzureDraenite02")
    :dropable(false)
    :pawnable(false)