TPL_UNIT.NPC_Token = UnitTpl()
    :speechExtra("immovable")
    :modelScale(1)
    :scale(1)
    :superposition("noAttack", 1)
    :superposition("invulnerable", 1)
    :itemSlot(false)
    :hp(100)
    :mp(0)
    :move(200)