local process = Process("enter")
process:onStart(function(this)
    Game():setWaterColor(Game():GD().diff)
    async.call(PlayerLocal(), function()
        audio(Vcm("portal"))
        UI_NinegridsAnimate:blackHole(1)
    end)
    time.setTimeout(1, function()
        this:next("looper")
    end)
end)
