local process = Process("setup")
process:onStart(function(this)
    Bgm():stop()
    time.ofDay(9)
    time.ofDayScale(1.3)
    Team("enemies")
        :name("探秘区怪异")
        :members({ 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 })
        :color(12)
        :nameSync(true)
        :colorSync(true)
    this:next("server")
end)
