TPL_UNIT.AuraTNTBarrel = UnitTpl()
    :name("炸药桶")
    :modelAlias("TNTBarrel")
    :icon("item/Barrel")
    :modelScale(1)
    :scale(1)
    :itemSlot(false)
    :superposition("noAttack", 1)
    :hp(100)
    :mp(0)
    :move(200)