TPL_UNIT.Adventurer_KnightFarstrider = UnitTpl("Centaur")
    :name("冒险者骑首部")
    :modelAlias("unit/HawkstriderKnightFarstrider")
    :icon("unit/TheCaptain")
    :modelScale(1)
    :scale(1.3)
    :superposition("invulnerable", 1)
    :attack(100)
    :mp(0)
    :move(200)