TPL_UNIT.BOSS_1 = UnitTpl("Garithos")
    :name("初生至泠(雷霆战鬼)")
    :modelAlias("hero/Wotlk_Dranosh_Saurfang")
    :icon("unit/CaptainRevenant")
    :modelScale(2)
    :scale(2.3)
    :hp(500)
    :mp(600)
    :move(250)
    :stature(180)
    :attackSpaceBase(1.8)
    :attackRange(200)
    :material(UNIT_MATERIAL.metal)
    :weaponSound("metal_chop_heavy")
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.steel))
    :enchantResistance(DAMAGE_TYPE.thunder, 30)
    :enchantResistance(DAMAGE_TYPE.water, 30)
    :enchantResistance(DAMAGE_TYPE.ice, 30)
    :enchantResistance(DAMAGE_TYPE.poison, -30)
TPL_UNIT.BOSS_2 = UnitTpl("Warlock")
    :name("洞悉至泠(噬灵妖怪)")
    :modelAlias("hero/Mindflayer")
    :icon("unit/Unbroken2")
    :modelScale(1.8)
    :scale(2)
    :hp(1000)
    :mp(1000)
    :move(225)
    :stature(200)
    :attackSpaceBase(1.6)
    :attackRange(700)
    :material(UNIT_MATERIAL.flesh)
    :weaponLength(150)
    :weaponHeight(170)
    :attackMode(AttackMode():mode("missile"):homing(true)
                            :missileModel("DevourMagicBirthMissile")
                            :damageType(DAMAGE_TYPE.dark)
                            :speed(1000):height(50))
    :enchantMaterial(DAMAGE_TYPE.dark)
    :enchantResistance(DAMAGE_TYPE.fire, 30)
    :enchantResistance(DAMAGE_TYPE.poison, 30)
    :enchantResistance(DAMAGE_TYPE.steel, 30)
    :enchantResistance(DAMAGE_TYPE.light, -30)
TPL_UNIT.BOSS_3 = UnitTpl("Tichondrius")
    :name("破灭至泠(狱炎爆蜥)")
    :modelAlias("hero/MoargOverlord1")
    :icon("unit/Overlord")
    :modelScale(1.6)
    :scale(3.3)
    :hp(2500)
    :mp(1500)
    :move(250)
    :stature(240)
    :attackSpaceBase(2.0)
    :attackRange(200)
    :material(UNIT_MATERIAL.rock)
    :weaponSound("metal_bash_heavy")
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.fire))
    :enchantResistance(DAMAGE_TYPE.rock, 30)
    :enchantResistance(DAMAGE_TYPE.wind, 30)
    :enchantResistance(DAMAGE_TYPE.grass, 30)
    :enchantResistance(DAMAGE_TYPE.water, -30)
TPL_UNIT.BOSS_4 = UnitTpl("HeroDreadLord")
    :name("觉醒至泠(人屠杀神)")
    :modelAlias("hero/Nightmare")
    :icon("unit/PurpleFullPlate")
    :modelScale(1.5)
    :scale(2)
    :hp(5000)
    :mp(2000)
    :move(260)
    :stature(200)
    :attackSpaceBase(1.5)
    :attackRange(190)
    :material(UNIT_MATERIAL.flesh)
    :weaponSound("metal_slice_heavy")
    :enchantResistance(DAMAGE_TYPE.light, 30)
    :enchantResistance(DAMAGE_TYPE.poison, 30)
    :enchantResistance(DAMAGE_TYPE.ice, 30)
    :enchantResistance(DAMAGE_TYPE.thunder, -30)
TPL_UNIT.BOSS_5 = UnitTpl("Shade")
    :name("最终BOSS")
    :modelAlias("hero/PestilantPrince")
    :icon("unit/PestilantPrince")
    :stature(220)
    :modelScale(2)
    :scale(2.4)
    :hp(500)
    :mp(200)
    :hpRegen(0)
    :mpRegen(3)
    :move(300)
    :attack(50)
    :attackSpaceBase(1.0)
    :defend(10)
    :enchantResistance(DAMAGE_TYPE.fire, 20)
    :enchantResistance(DAMAGE_TYPE.water, 20)
    :enchantResistance(DAMAGE_TYPE.ice, 20)
    :enchantResistance(DAMAGE_TYPE.wind, 20)
    :enchantResistance(DAMAGE_TYPE.light, 20)
    :enchantResistance(DAMAGE_TYPE.poison, 20)
    :enchantResistance(DAMAGE_TYPE.thunder, 20)
    :enchantResistance(DAMAGE_TYPE.rock, 20)
    :enchantResistance(DAMAGE_TYPE.grass, 20)
    :enchantResistance(DAMAGE_TYPE.steel, 20)