TPL_UNIT.Bandit = UnitTpl("Bandit")
    :name("盗贼")
    :modelAlias("Bandit")
    :icon("unit/Bandit")
    :modelScale(1)
    :scale(1)
    :itemSlot(false)
    :mp(0)
    :move(300)
    :weaponSound("metal_bash_medium")
TPL_UNIT.BanditSpearThrower = UnitTpl("Bandit")
    :name("窃贼")
    :modelAlias("BanditSpearThrower")
    :icon("unit/BanditSpearThrower")
    :modelScale(1)
    :scale(1)
    :itemSlot(false)
    :mp(0)
    :move(250)
    :attackMode(AttackMode():mode("missile"):missileModel("BanditMissile"):speed(1200):height(10))
    :attackRange(300)