TPL_UNIT.Rifleman = UnitTpl("Rifleman")
    :name("火枪兵")
    :modelAlias("Rifleman")
    :modelScale(1)
    :scale(1)
    :itemSlot(false)
    :attackRange(400)
    :mp(0)
    :move(220)
TPL_UNIT.Knight = UnitTpl("Knight")
    :name("骑士")
    :modelAlias("Knight")
    :modelScale(1)
    :scale(1.3)
    :itemSlot(false)
    :attackRange(120)
    :mp(0)
    :move(330)
TPL_UNIT.BlackDreadRevenantAlterTC = UnitTpl("Priest")
    :name("漆黑术士")
    :modelAlias("unit/DreadRevenantAlterTC")
    :modelScale(1)
    :scale(1)
    :itemSlot(false)
    :attackRange(600)
    :mp(0)
    :move(250)
    :attackMode(AttackMode():mode("missile"):missileModel("NecromancerMissile"):speed(750):height(10):damageType(DAMAGE_TYPE.dark))
TPL_UNIT.BlackChaplain = UnitTpl("Footman")
    :name("漆黑剑士")
    :modelAlias("unit/Chaplain")
    :modelScale(1)
    :scale(1)
    :itemSlot(false)
    :mp(0)
    :move(300)
    :weaponSound("metal_slice_heavy")
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.poison))
TPL_UNIT.BlackCrimsonCaptain = UnitTpl("GryphonRider")
    :name("漆黑锤兵")
    :modelAlias("unit/CrimsonCaptain")
    :modelScale(1)
    :scale(1.1)
    :itemSlot(false)
    :mp(0)
    :move(280)
    :weaponSound("metal_bash_heavy")
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.steel))
TPL_UNIT.BlackMageRevenant = UnitTpl("Knight")
    :name("漆黑火爆军")
    :modelAlias("unit/MageRevenant")
    :modelScale(1.2)
    :scale(1.4)
    :itemSlot(false)
    :mp(0)
    :move(325)
    :weaponSound("metal_chop_heavy")
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.fire))
