TPL_UNIT.Ent = UnitTpl("Ent")
    :name("树人")
    :modelAlias("Ent")
    :modelScale(1.0)
    :scale(1.3)
    :itemSlot(false)
    :move(200)
    :weaponSound("wood_bash_light")
    :material(UNIT_MATERIAL.wood)
    :enchantMaterial(DAMAGE_TYPE.grass)
    :enchantImmune(DAMAGE_TYPE.grass, 1)
    :attackRange(100)
    :attackSpaceBase(1.5)
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.grass))
TPL_UNIT.AncientProtector = UnitTpl("Ent")
    :name("远古守卫")
    :modelAlias("AncientProtector")
    :modelScale(0.8)
    :scale(1.7)
    :itemSlot(false)
    :move(100)
    :weaponSound("wood_bash_heavy")
    :material(UNIT_MATERIAL.wood)
    :enchantMaterial(DAMAGE_TYPE.grass)
    :enchantImmune(DAMAGE_TYPE.grass, 1)
    :enchantImmune(DAMAGE_TYPE.grass, 1)
    :attackRange(200)
    :attackSpaceBase(2.5)
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.grass))
TPL_UNIT.CorruptedEnt = UnitTpl("Ent")
    :name("堕落树人")
    :modelAlias("CorruptedEnt")
    :modelScale(1.0)
    :scale(1.3)
    :itemSlot(false)
    :move(200)
    :weaponSound("wood_bash_light")
    :material(UNIT_MATERIAL.wood)
    :enchantMaterial(DAMAGE_TYPE.grass)
    :enchantImmune(DAMAGE_TYPE.grass, 1)
    :attackRange(100)
    :attackSpaceBase(1.5)
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.grass))
TPL_UNIT.CorruptedTreeOfLife = UnitTpl("Ent")
    :name("堕邪树")
    :modelAlias("unit/Archdruidnightmare")
    :modelScale(0.7)
    :scale(1.7)
    :itemSlot(false)
    :move(100)
    :weaponSound("wood_bash_heavy")
    :material(UNIT_MATERIAL.wood)
    :enchantMaterial(DAMAGE_TYPE.grass)
    :enchantImmune(DAMAGE_TYPE.grass, 1)
    :enchantImmune(DAMAGE_TYPE.dark, 1)
    :attackRange(200)
    :attackSpaceBase(2)
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.dark))
TPL_UNIT.TinkerRobot = UnitTpl("ClockwerkGoblin")
    :name("机器人")
    :modelAlias("TinkerRobot")
    :modelScale(1.0)
    :scale(1.0)
    :itemSlot(false)
    :move(220)
    :weaponSound("metal_chop_medium")
    :material(UNIT_MATERIAL.metal)
    :enchantMaterial(DAMAGE_TYPE.steel)
    :attackRange(100)
    :attackSpaceBase(1.5)
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.steel))