TPL_UNIT.IcePolarBear = UnitTpl("Furbolg")
    :name("大雪熊")
    :icon("unit/FrostBear")
    :modelAlias("PolarBear")
    :modelScale(1)
    :scale(1.5)
    :weaponSound("wood_bash_heavy")
    :itemSlot(false)
    :hp(100)
    :mp(0)
    :move(240)
    :attackRange(125)
TPL_UNIT.IcePolarBear2 = UnitTpl("Furbolg")
    :name("装甲雪熊")
    :icon("unit/PolarBro2")
    :modelAlias("unit/ArmoredPolarBear")
    :modelScale(1)
    :scale(1.5)
    :weaponSound("wood_bash_heavy")
    :itemSlot(false)
    :hp(100)
    :mp(0)
    :move(230)
    :attackRange(125)
TPL_UNIT.IceBaiHu = UnitTpl("Wolf")
    :name("北冰虎")
    :icon("unit/MountWhiteTiger")
    :modelAlias("unit/BaiHu")
    :modelScale(1)
    :scale(1.3)
    :weaponSound("wood_bash_medium")
    :itemSlot(false)
    :hp(100)
    :mp(0)
    :move(300)
    :attackRange(100)