TPL_UNIT.ABILITY_SOUL_PandaEarth = UnitTpl("EarthPandarenBrewmaster")
    :name("熊猫大地")
    :modelAlias("EarthPandarenBrewmaster")
    :icon("unit/PandaEarthBrewMaster")
    :modelScale(1.0)
    :scale(1.5)
    :itemSlot(false)
    :move(250)
    :weaponSound("rock_bash_heavy")
    :enchantMaterial(DAMAGE_TYPE.rock)
    :enchantImmune(DAMAGE_TYPE.rock, 1)
    :attackRange(100)
    :attackSpaceBase(2)
    :rgba(255, 255, 255, 150)
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.rock))
    :prop("sp", "防御+3，10%几率眩晕2秒"):defend(3):stun(2):odds("stun", 10)
TPL_UNIT.ABILITY_SOUL_PandaStorm = UnitTpl("StormPandarenBrewmaster")
    :name("熊猫雷暴")
    :modelAlias("StormPandarenBrewmaster")
    :icon("unit/PandaStorm")
    :modelScale(1.0)
    :scale(1.5)
    :itemSlot(false)
    :move(250)
    :enchantMaterial(DAMAGE_TYPE.thunder)
    :enchantImmune(DAMAGE_TYPE.thunder, 1)
    :attackRange(250)
    :attackSpaceBase(2)
    :rgba(255, 255, 255, 150)
    :attackMode(AttackMode():mode("lightning"):lightningType(LIGHTNING_TYPE.thunderShot):damageType(DAMAGE_TYPE.thunder):radius(400):scatter(3))
    :prop("sp", "散射3木飙雷电攻击")
TPL_UNIT.ABILITY_SOUL_PandaFire = UnitTpl("FirePandarenBrewmaster")
    :name("熊猫烈焰")
    :modelAlias("FirePandarenBrewmaster")
    :icon("unit/PandaFireBrewMaster")
    :modelScale(1.0)
    :scale(1.5)
    :itemSlot(false)
    :move(250)
    :weaponSound("metal_slice_medium")
    :weaponHeight(70)
    :enchantMaterial(DAMAGE_TYPE.fire)
    :enchantImmune(DAMAGE_TYPE.fire, 1)
    :attackRange(175)
    :attackSpaceBase(2)
    :rgba(255, 255, 255, 150)
    :attackMode(AttackMode():mode("missile"):missileModel("slash/RedBigCut"):damageType(DAMAGE_TYPE.fire))
    :prop("sp", "20%几率暴击130%伤害"):crit(30):odds("crit", 20)
TPL_UNIT.ABILITY_SOUL_PandaArcher = UnitTpl("FirePandarenBrewmaster")
    :name("熊猫铩羽")
    :modelAlias("pandaren/Pandaren_Archer")
    :icon("unit/Pandaren_Archer")
    :modelScale(1.0)
    :scale(1.4)
    :itemSlot(false)
    :move(200)
    :weaponHeight(80)
    :attackRange(500)
    :attackSpaceBase(2)
    :rgba(255, 255, 255, 150)
    :attackMode(AttackMode():mode("missile"):missileModel("missile/Bloodstone_Arrow_Bloodless"):damageType(DAMAGE_TYPE.steel):gatlin(1))
    :prop("sp", "射击时带有额外1支箭矢")
TPL_UNIT.ABILITY_SOUL_PandaHarvester = UnitTpl("EarthPandarenBrewmaster")
    :name("熊猫药师")
    :modelAlias("pandaren/Pandaren_Harvester")
    :icon("unit/PandaStormBrewMaster")
    :modelScale(1.0)
    :scale(1.4)
    :itemSlot(false)
    :move(200)
    :weaponSound("metal_chop_light")
    :attackRange(100)
    :attackSpaceBase(2)
    :rgba(255, 255, 255, 150)
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.poison))
    :onEvent(EVENT.Unit.Attack, function(attackData) attackData.targetUnit:defend("-=2;5") end)
    :prop("sp", "攻击破防2点持续5秒")
TPL_UNIT.ABILITY_SOUL_PandaHonorguard = UnitTpl("EarthPandarenBrewmaster")
    :name("熊猫剑光")
    :modelAlias("pandaren/Pandaren_Honorguard")
    :icon("unit/Pandaren_Honorguard")
    :modelScale(1.0)
    :scale(1.4)
    :itemSlot(false)
    :move(200)
    :weaponSound("metal_slice_light")
    :weaponHeight(80)
    :attackRange(150)
    :attackSpaceBase(1.5)
    :rgba(255, 255, 255, 150)
    :attackMode(AttackMode():mode("missile"):missileModel("slash/MessyKnife"):damageType(DAMAGE_TYPE.light))
    :onEvent(EVENT.Unit.Attack, function(attackData) attackData.targetUnit:enchantResistance(DAMAGE_TYPE.dark, "-=3;5") end)
    :prop("sp", "攻击频率加快，攻击降低暗抗3%持续5秒")
TPL_UNIT.ABILITY_SOUL_PandaSage = UnitTpl("EarthPandarenBrewmaster")
    :name("熊猫泉老")
    :modelAlias("pandaren/Pandaren_Sage")
    :icon("unit/Pandaren_Sage")
    :modelScale(1.0)
    :scale(1.4)
    :itemSlot(false)
    :move(150)
    :weaponHeight(60)
    :attackRange(350)
    :attackSpaceBase(2)
    :rgba(255, 255, 255, 150)
    :attackMode(AttackMode():mode("missile"):missileModel("missile/Bubbles"):damageType(DAMAGE_TYPE.water):speed(300))
    :defend(-15)
    :onEvent(EVENT.Unit.Attack, function(attackData) attackData.targetUnit:move("-=20;5") end)
    :prop("sp", "攻击可减慢木飙移动20持续5秒")
TPL_UNIT.ABILITY_SOUL_PandaVulture = UnitTpl("Furbolg")
    :name("熊猫芳竹")
    :modelAlias("pandaren/Pandaren_Vulture")
    :icon("unit/PandaTaunt")
    :modelScale(1.0)
    :scale(1.1)
    :itemSlot(false)
    :move(150)
    :flyHeight(150)
    :weaponHeight(30)
    :attackRange(400)
    :attackSpaceBase(2.2)
    :rgba(255, 255, 255, 150)
    :attackMode(AttackMode():mode("missile"):missileModel("missile/Seed_Shot"):damageType(DAMAGE_TYPE.grass):speed(250))
    :defend(-15)
    :onEvent(EVENT.Unit.Attack, function(attackData) attackData.targetUnit:attack("-=15;5") end)
    :prop("sp", "攻击可减慢木飙攻击15持续5秒")