TPL_UNIT.Spider = UnitTpl("Spider")
    :name("小蜘蛛")
    :icon("unit/Spider")
    :modelAlias("Spider")
    :modelScale(0.95)
    :scale(1.1)
    :weaponSound("wood_bash_light")
    :mp(0)
    :move(180)
    :attackRange(100)
TPL_UNIT.SpiderBlack = UnitTpl("Spider")
    :name("小黑蛛")
    :icon("unit/SpiderBlack")
    :modelAlias("SpiderBlack")
    :modelScale(1)
    :scale(1.2)
    :weaponSound("wood_bash_medium")
    :mp(0)
    :move(180)
    :attackRange(100)
TPL_UNIT.SpiderBlue = UnitTpl("Spider")
    :name("小蓝冰蛛")
    :icon("unit/SpiderBlue")
    :modelAlias("SpiderBlue")
    :modelScale(1.2)
    :scale(1.3)
    :attackMode(AttackMode():mode("missile"):missileModel("CryptFiendMissileTarget"):speed(600):height(0)
                            :damageType(DAMAGE_TYPE.ice):damageTypeLevel(0))
    :mp(0)
    :move(160)
    :attackRange(250)
TPL_UNIT.SpiderGreen = UnitTpl("Spider")
    :name("小绿毒蛛")
    :icon("unit/SpiderGreen")
    :modelAlias("SpiderGreen")
    :modelScale(1.2)
    :scale(1.3)
    :attackMode(AttackMode():mode("missile"):missileModel("BottleImpact"):speed(1000):height(0)
                            :damageType(DAMAGE_TYPE.poison):damageTypeLevel(0))
    :mp(0)
    :move(160)
    :attackRange(150)
