TPL_UNIT.MurlocYellow = UnitTpl("Murloc")
    :name("小鱼人")
    :icon("unit/Murloc")
    :modelAlias("MurlocYellow")
    :modelScale(1.0)
    :scale(1.0)
    :weaponSound("wood_bash_light")
    :mp(0)
    :attackRange(100)
    :move(170)
TPL_UNIT.MurlocOrange = UnitTpl("Murloc")
    :name("小鱼人")
    :icon("unit/Murloc")
    :modelAlias("MurlocOrange")
    :modelScale(1.0)
    :scale(1.0)
    :weaponSound("wood_bash_light")
    :mp(0)
    :attackRange(100)
    :move(170)
TPL_UNIT.MurlocGreen = UnitTpl("Murloc")
    :name("小鱼人")
    :icon("unit/MurlocMutant")
    :modelAlias("MurlocGreen")
    :modelScale(1.0)
    :scale(1.0)
    :weaponSound("wood_bash_light")
    :mp(0)
    :attackRange(100)
    :move(170)
TPL_UNIT.MurlocCyan = UnitTpl("Murloc")
    :name("小鱼人")
    :icon("unit/MurlocMutant")
    :modelAlias("MurlocCyan")
    :modelScale(1.0)
    :scale(1.0)
    :weaponSound("wood_bash_light")
    :mp(0)
    :attackRange(100)
    :move(170)
TPL_UNIT.MurlocBlue = UnitTpl("Murloc")
    :name("小鱼人")
    :icon("unit/MurlocFleshEater")
    :modelAlias("MurlocBlue")
    :modelScale(1.0)
    :scale(1.0)
    :weaponSound("wood_bash_light")
    :mp(0)
    :attackRange(100)
    :move(200)
TPL_UNIT.MurlocDeepBlue = UnitTpl("Murloc")
    :name("小鱼人")
    :icon("unit/MurlocFleshEater")
    :modelAlias("MurlocDeepBlue")
    :modelScale(1.0)
    :scale(1.0)
    :weaponSound("wood_bash_light")
    :mp(0)
    :attackRange(100)
    :move(200)
TPL_UNIT.MurlocPurple = UnitTpl("Murloc")
    :name("小鱼人")
    :icon("unit/MurlocNightCrawler")
    :modelAlias("MurlocPurple")
    :modelScale(1.0)
    :scale(1.0)
    :weaponSound("wood_bash_light")
    :mp(0)
    :attackRange(100)
    :move(200)
TPL_UNIT.MurlocNight = UnitTpl("Murloc")
    :name("小鱼人")
    :icon("unit/MurlocNightCrawler")
    :modelAlias("MurlocNight")
    :modelScale(1.0)
    :scale(1.0)
    :weaponSound("wood_bash_light")
    :mp(0)
    :attackRange(100)
    :move(220)
TPL_UNIT.MurlocShadow = UnitTpl("Murloc")
    :name("小鱼人")
    :icon("unit/MurlocNightCrawler")
    :modelAlias("MurlocShadow")
    :modelScale(1.0)
    :scale(1.0)
    :weaponSound("wood_bash_light")
    :mp(0)
    :attackRange(100)
    :move(220)
TPL_UNIT.Turtle = UnitTpl("GiantSeaTurtle")
    :name("绿龟")
    :icon("unit/SeaTurtleGreen")
    :modelAlias("SeaTurtleYG")
    :modelScale(0.8)
    :scale(1.6)
    :weaponSound("wood_bash_heavy")
    :mp(0)
    :attackRange(100)
    :move(180)
TPL_UNIT.SeaTurtleRed = UnitTpl("GiantSeaTurtle")
    :name("红龟")
    :icon("unit/SeaTurtleRed")
    :modelAlias("SeaTurtleRed")
    :modelScale(1.0)
    :scale(1.3)
    :weaponSound("wood_bash_heavy")
    :mp(0)
    :attackRange(100)
    :move(180)
TPL_UNIT.SeaSiren = UnitTpl("NagaSiren")
    :name("海妖")
    :icon("unit/NagaSummoner")
    :modelAlias("NagaSummoner")
    :modelScale(1.0)
    :scale(1.3)
    :weaponSound("metal_slice_medium")
    :mp(0)
    :attackRange(100)
    :move(230)
TPL_UNIT.SeaSnapDragon = UnitTpl("SnapDragon")
    :name("海龙")
    :icon("unit/SnapDragon")
    :modelAlias("SnapDragon")
    :modelScale(1.0)
    :scale(1.6)
    :weaponSound("wood_bash_medium")
    :mp(0)
    :attackRange(100)
    :move(240)
TPL_UNIT.SeaMyrmidon = UnitTpl("NagaMyrmidon")
    :name("巨海战士")
    :icon("unit/NagaMyrmidon")
    :modelAlias("NagaMyrmidon")
    :modelScale(1.0)
    :scale(1.4)
    :weaponSound("metal_bash_heavy")
    :mp(0)
    :attackRange(120)
    :move(230)
TPL_UNIT.SeaRoyalGuard = UnitTpl("NagaRoyalGuard")
    :name("皇海战士")
    :icon("unit/NagaMyrmidonRoyalGuard")
    :modelAlias("NagaRoyalGuard")
    :modelScale(1.0)
    :scale(1.4)
    :weaponSound("metal_bash_heavy")
    :mp(0)
    :attackRange(120)
    :move(260)
