TPL_UNIT.Kobold = UnitTpl("Kobold")
    :name("狗头人")
    :modelAlias("Kobold")
    :icon("unit/Kobold")
    :modelScale(1)
    :scale(1)
    :itemSlot(false)
    :mp(0)
    :move(400)
    :weaponSound("metal_chop_medium")
TPL_UNIT.KoboldGeomancer = UnitTpl("Kobold")
    :name("狗头法师")
    :modelAlias("KoboldGeomancer")
    :icon("unit/KoboldGeomancer")
    :modelScale(1)
    :scale(1)
    :itemSlot(false)
    :mp(0)
    :move(350)
    :attackMode(AttackMode():mode("missile"):missileModel("OrbCorruptionMissile"):speed(900):height(20))
    :attackRange(400)
TPL_UNIT.Tauren = UnitTpl("Tauren")
    :name("牛头人")
    :modelAlias("Tauren")
    :icon("unit/Tauren")
    :modelScale(1)
    :scale(1.4)
    :itemSlot(false)
    :mp(0)
    :move(250)
    :weaponSound("wood_bash_heavy")
TPL_UNIT.SpiritWalker = UnitTpl("SpiritWalker")
    :name("白毛牛")
    :modelAlias("SpiritWalker")
    :icon("unit/SpiritWalker")
    :modelScale(1.5)
    :scale(1.6)
    :itemSlot(false)
    :mp(0)
    :move(330)
    :weaponSound("wood_bash_medium")
TPL_UNIT.Arachnathid = UnitTpl("Gnoll")
    :name("蝎子")
    :modelAlias("Arachnathid")
    :modelScale(1.0)
    :scale(1.4)
    :itemSlot(false)
    :mp(0)
    :move(260)
    :attackSpaceBase(1.7)
    :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.poison))
    :attackRange(100)
TPL_UNIT.EarthElemental = UnitTpl()
    :name("沙人")
    :modelAlias("unit/EarthElemental")
    :icon("unit/NatureEarthElementalTotem")
    :modelScale(1)
    :scale(1.1)
    :itemSlot(false)
    :mp(0)
    :move(250)
    :attackMode(AttackMode():mode("missile"):missileModel("TreantMissile"):speed(1000))
    :attackRange(300)