TPL_UNIT.Militia = UnitTpl("Peasant")
    :name("民兵")
    :modelAlias("Militia")
    :icon("unit/Militia")
    :modelScale(1)
    :scale(1)
    :itemSlot(false)
    :mp(0)
    :move(250)
TPL_UNIT.MilitiaUp = UnitTpl("Peasant")
    :name("斧头兵")
    :modelAlias("unit/ChaosWarrior")
    :icon("unit/Berengar")
    :modelScale(1)
    :scale(1)
    :itemSlot(false)
    :mp(0)
    :move(300)