TPL_UNIT.SCENE = UnitTpl()
    :speechExtra("immovable")
    :name("未知场景")
    :modelScale(1)
    :scale(1.0)
    :itemSlot(false)
    :superposition("noAttack", 1)
    :hp(50)
    :mp(0)
    :corpse(0)