TPL_SOUL_ATTR = {
    hp = 1000,
    mp = 400,
    hpRegen = 0,
    mpRegen = 4,
    move = 300,
    attack = 100,
    attackSpaceBase = 1.0,
    attackRange = 100,
    defend = 20,
}
TPL_SOUL = {
    UnitTpl("Arthas")
        :name("人泠(钢剑帝)")
        :icon("unit/Arthas")
        :modelAlias("hero/PaladinSword")
        :modelScale(1.0)
        :scale(1.2)
        :material(UNIT_MATERIAL.metal)
        :weaponSound("metal_slice_medium")
        :attackMode(AttackMode():mode("common"))
        :stature(70)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp)
        :mp(TPL_SOUL_ATTR.mp)
        :move(TPL_SOUL_ATTR.move)
        :attack(TPL_SOUL_ATTR.attack)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase)
        :attackRange(TPL_SOUL_ATTR.attackRange)
        :defend(TPL_SOUL_ATTR.defend)
        :prop("sp", "护盾300点")
        :shield(300),
    UnitTpl("Sylvanus")
        :name("弓泠(追风使)")
        :icon("unit/BrightRanger")
        :modelAlias("SylvanusWindrunner")
        :modelScale(1.0)
        :scale(1.0)
        :material(UNIT_MATERIAL.flesh)
        :weaponHeight(55)
        :attackMode(AttackMode():mode("missile")
                                :missileModel("ArrowMissile")
                                :speed(1100):height(100))
        :stature(40)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp - 240)
        :mp(TPL_SOUL_ATTR.mp + 80)
        :move(TPL_SOUL_ATTR.move + 50)
        :attack(TPL_SOUL_ATTR.attack - 30)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.4)
        :attackRange(TPL_SOUL_ATTR.attackRange + 650)
        :defend(TPL_SOUL_ATTR.defend - 11)
        :prop("sp", "攻速提升8%")
        :attackSpeed(8),
    UnitTpl("HeroMountainKing")
        :name("锤泠(矮山王)")
        :icon("unit/HeroMountainKing")
        :modelAlias("HeroMountainKing")
        :modelScale(1.2)
        :scale(1.4)
        :material(UNIT_MATERIAL.metal)
        :attackMode(AttackMode():mode("common"))
        :weaponSound("metal_bash_heavy")
        :stature(40)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 550)
        :mp(TPL_SOUL_ATTR.mp - 200)
        :move(TPL_SOUL_ATTR.move - 60)
        :attack(TPL_SOUL_ATTR.attack + 60)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.6)
        :attackRange(TPL_SOUL_ATTR.attackRange)
        :defend(TPL_SOUL_ATTR.defend + 25)
        :prop("sp", "5%几率击晕1.25秒")
        :stun(1.25):odds("stun", 5),
    UnitTpl("herowarden")
        :name("杀泠(绝命针)")
        :icon("unit/HeroWarden")
        :modelAlias("hero/CordanaFelsong")
        :modelScale(1.0)
        :scale(1.1)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_slice_light")
        :attackMode(AttackMode():mode("missile")
                                :missileModel("GargoyleMissile")
                                :speed(1500):height(0))
        :stature(55)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp - 270)
        :mp(TPL_SOUL_ATTR.mp + 40)
        :move(TPL_SOUL_ATTR.move + 15)
        :attack(TPL_SOUL_ATTR.attack)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.3)
        :attackRange(TPL_SOUL_ATTR.attackRange + 150)
        :defend(TPL_SOUL_ATTR.defend - 22)
        :prop("sp", "回避提升14%")
        :avoid(14),
    UnitTpl("Proudmoore")
        :name("边泠(御船海士)")
        :icon("unit/Captain")
        :modelAlias("Proudmoore")
        :modelScale(1.1)
        :scale(1.2)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_slice_medium")
        :attackMode(AttackMode():mode("common"))
        :stature(50)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 310)
        :mp(TPL_SOUL_ATTR.mp + 80)
        :move(TPL_SOUL_ATTR.move - 20)
        :attack(TPL_SOUL_ATTR.attack + 10)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.2)
        :attackRange(TPL_SOUL_ATTR.attackRange)
        :defend(TPL_SOUL_ATTR.defend + 6)
        :prop("sp", "眩晕抗性提升25%")
        :resistance("stun", 25),
    UnitTpl("Furion")
        :name("奥术泠(鹿法)")
        :icon("unit/Furion")
        :modelAlias("Furion")
        :modelScale(1.0)
        :scale(1.1)
        :material(UNIT_MATERIAL.wood)
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("SorceressMissile")
                                :speed(600):height(50))
        :stature(50)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 30)
        :mp(TPL_SOUL_ATTR.mp + 240)
        :move(TPL_SOUL_ATTR.move - 20)
        :attack(TPL_SOUL_ATTR.attack - 10)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase)
        :attackRange(TPL_SOUL_ATTR.attackRange + 450)
        :defend(TPL_SOUL_ATTR.defend - 6)
        :prop("sp", "治疗提升18%")
        :cure(18),
    UnitTpl("HeroFarSeer")
        :name("先泠(先知)")
        :icon("unit/HeroFarSeer")
        :modelAlias("HeroFarSeer")
        :modelScale(1.0)
        :scale(1.5)
        :material(UNIT_MATERIAL.flesh)
        :attackMode(AttackMode():mode("missile")
                                :missileModel("SteamMissile")
                                :speed(1100):height(0)
                                :damageType(DAMAGE_TYPE.light))
        :stature(55)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen + 6)
        :hp(TPL_SOUL_ATTR.hp)
        :mp(TPL_SOUL_ATTR.mp + 140)
        :move(TPL_SOUL_ATTR.move)
        :attack(TPL_SOUL_ATTR.attack)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.2)
        :attackRange(TPL_SOUL_ATTR.attackRange + 500)
        :defend(TPL_SOUL_ATTR.defend - 7)
        :prop("sp", "额外900点视野，MP恢复+6")
        :sight("+=900"),
    UnitTpl("Beastmaster")
        :name("野兽泠(兽王)")
        :icon("unit/BeastMaster")
        :modelAlias("hero/LKSBYQ5")
        :modelScale(1.2)
        :scale(1.5)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_chop_heavy")
        :attackMode(AttackMode():mode("common"))
        :stature(100)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 440)
        :mp(TPL_SOUL_ATTR.mp - 150)
        :move(TPL_SOUL_ATTR.move - 35)
        :attack(TPL_SOUL_ATTR.attack + 30)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.1)
        :attackRange(TPL_SOUL_ATTR.attackRange)
        :defend(TPL_SOUL_ATTR.defend + 11)
        :prop("sp", "攻击提升12%")
        :mutation("attack", 12),
    UnitTpl("HeroDeathKnight")
        :name("亡泠(死骑)")
        :icon("unit/HeroDeathKnight")
        :modelAlias("HeroDeathKnight")
        :modelScale(1.0)
        :scale(1.5)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_slice_heavy")
        :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.ice))
        :stature(50)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 500)
        :mp(TPL_SOUL_ATTR.mp + 100)
        :move(TPL_SOUL_ATTR.move - 25)
        :attack(TPL_SOUL_ATTR.attack + 33)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.4)
        :attackRange(TPL_SOUL_ATTR.attackRange)
        :defend(TPL_SOUL_ATTR.defend + 10)
        :prop("sp", "命中提升30%，火抗性降低35%")
        :aim(30)
        :enchantResistance(DAMAGE_TYPE.fire, -35),
    UnitTpl("BloodElfWorker")
        :name("影泠(无踪刺客)")
        :icon("unit/ArcaneHuntress")
        :modelAlias("hero/BEArcaneHuntress")
        :modelScale(1.0)
        :scale(1.1)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_slice_light")
        :attackMode(AttackMode():mode("common"))
        :stature(45)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp - 400)
        :mp(TPL_SOUL_ATTR.mp + 45)
        :move(TPL_SOUL_ATTR.move + 40)
        :attack(TPL_SOUL_ATTR.attack + 80)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.4)
        :attackRange(TPL_SOUL_ATTR.attackRange)
        :defend(TPL_SOUL_ATTR.defend - 25)
        :prop("sp", "攻速提升6%，钢抗性降低35%")
        :attackSpeed(6)
        :enchantResistance(DAMAGE_TYPE.steel, -35),
    UnitTpl("HeroTinker")
        :name("匠泠(军技师)")
        :icon("unit/HeroTinker")
        :modelAlias("HeroTinker")
        :modelScale(1.0)
        :scale(1.4)
        :material(UNIT_MATERIAL.metal)
        :attackMode(AttackMode():mode("missile"):homing(true):homing(true)
                                :missileModel("TinkerRocketMissile")
                                :speed(800):height(300))
        :stature(55)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 180)
        :mp(TPL_SOUL_ATTR.mp + 110)
        :move(TPL_SOUL_ATTR.move + 10)
        :attack(TPL_SOUL_ATTR.attack + 50)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.7)
        :attackRange(TPL_SOUL_ATTR.attackRange + 300)
        :defend(TPL_SOUL_ATTR.defend + 1)
        :prop("sp", "钢体质，水、冰抗性降低20%")
        :enchantMaterial(DAMAGE_TYPE.steel)
        :enchantResistance(DAMAGE_TYPE.water, -20)
        :enchantResistance(DAMAGE_TYPE.ice, -20),
    UnitTpl("Nerubian")
        :name("蛛泠(牙杀至咬)")
        :icon("unit/Spider")
        :modelAlias("hero/Dark_Spider")
        :modelScale(1.0)
        :scale(1.5)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("wood_bash_heavy")
        :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.poison))
        :stature(20)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp - 190)
        :mp(TPL_SOUL_ATTR.mp + 40)
        :move(TPL_SOUL_ATTR.move + 30)
        :attack(TPL_SOUL_ATTR.attack + 20)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.1)
        :attackRange(TPL_SOUL_ATTR.attackRange + 125)
        :defend(TPL_SOUL_ATTR.defend - 12)
        :prop("sp", "伤害提升13%|n火、岩抗性降低24%")
        :damageIncrease(13)
        :enchantResistance(DAMAGE_TYPE.rock, -24)
        :enchantResistance(DAMAGE_TYPE.fire, -24),
    UnitTpl("SeaWitch")
        :name("蛇妖泠(美杜莎)")
        :icon("unit/NagaSeaWitch")
        :modelAlias("HeroNagaSeawitch")
        :modelScale(1.0)
        :scale(1.5)
        :material(UNIT_MATERIAL.flesh)
        :weaponHeight(70)
        :attackMode(AttackMode():mode("missile")
                                :missileModel("NagaArrowMissile")
                                :speed(1300):height(50))
        :stature(70)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 100)
        :mp(TPL_SOUL_ATTR.mp + 220)
        :move(TPL_SOUL_ATTR.move - 15)
        :attack(TPL_SOUL_ATTR.attack + 10)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.1)
        :attackRange(TPL_SOUL_ATTR.attackRange + 500)
        :defend(TPL_SOUL_ATTR.defend + 14)
        :prop("sp", "两栖移动，草、雷、风抗性降低10%")
        :moveType(UNIT_MOVE_TYPE.amphibious)
        :enchantResistance(DAMAGE_TYPE.grass, -10)
        :enchantResistance(DAMAGE_TYPE.thunder, -10)
        :enchantResistance(DAMAGE_TYPE.wind, -10),
    UnitTpl("HeroKeeperoftheGrove")
        :name("树泠(森林老鹿)")
        :icon("unit/KeeperOfTheGrove")
        :keepAnimation("stand channel")
        :modelAlias("HeroKeeperoftheGrove")
        :modelScale(1.0)
        :scale(1.5)
        :material(UNIT_MATERIAL.wood)
        :weaponLength(80)
        :weaponHeight(70)
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("KeeperGroveMissile")
                                :speed(900):height(50))
        :stature(80)
        :hpRegen(TPL_SOUL_ATTR.hpRegen + 3)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 130)
        :mp(TPL_SOUL_ATTR.mp + 80)
        :move(TPL_SOUL_ATTR.move - 20)
        :attack(TPL_SOUL_ATTR.attack + 25)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.5)
        :attackRange(TPL_SOUL_ATTR.attackRange + 550)
        :defend(TPL_SOUL_ATTR.defend + 5)
        :prop("sp", "HP恢复+3，草体质|n毒、火、冰抗性降低15%")
        :enchantMaterial(DAMAGE_TYPE.grass)
        :enchantResistance(DAMAGE_TYPE.fire, -15)
        :enchantResistance(DAMAGE_TYPE.poison, -15)
        :enchantResistance(DAMAGE_TYPE.ice, -15),
    UnitTpl("HeroBladeMaster")
        :name("剑泠(疾风)")
        :icon("unit/HeroBlademaster")
        :castAnimation("attack slam")
        :keepAnimation("attack slam")
        :modelAlias("HeroBladeMaster")
        :modelScale(1.0)
        :scale(1.2)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_slice_medium")
        :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.wind))
        :stature(65)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp)
        :mp(TPL_SOUL_ATTR.mp)
        :move(TPL_SOUL_ATTR.move + 20)
        :attack(TPL_SOUL_ATTR.attack + 70)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.2)
        :attackRange(TPL_SOUL_ATTR.attackRange)
        :defend(TPL_SOUL_ATTR.defend)
        :prop("sp", "风强化25%|n风抗性提升50%，冰抗性降低40%")
        :enchantResistance(DAMAGE_TYPE.wind, 50)
        :enchantResistance(DAMAGE_TYPE.ice, -40)
        :enchant(DAMAGE_TYPE.wind, 25),
    UnitTpl("ChaosGrunt")
        :name("狂泠(战)")
        :icon("unit/ChaosWolfRider")
        :modelAlias("hero/WarlordChaos")
        :modelScale(1.2)
        :scale(1.5)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_bash_heavy")
        :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.steel))
        :stature(80)
        :hpRegen(TPL_SOUL_ATTR.hpRegen + 4)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 750)
        :mp(TPL_SOUL_ATTR.mp - 230)
        :move(TPL_SOUL_ATTR.move - 45)
        :attack(TPL_SOUL_ATTR.attack + 125)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 1.0)
        :attackRange(TPL_SOUL_ATTR.attackRange + 100)
        :defend(TPL_SOUL_ATTR.defend + 18)
        :prop("sp", "HP恢复+4|n钢抗性提升40%，水抗性降低45%")
        :enchantResistance(DAMAGE_TYPE.steel, 40)
        :enchantResistance(DAMAGE_TYPE.water, -45),
    UnitTpl("HeroLich")
        :name("霜泠(巫妖)")
        :icon("unit/HeroLich")
        :keepAnimation("stand channel")
        :modelAlias("HeroLich")
        :modelScale(1.0)
        :scale(1.2)
        :material(UNIT_MATERIAL.flesh)
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("LichMissile")
                                :damageType(DAMAGE_TYPE.ice)
                                :speed(800):height(50))
        :stature(70)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen + 3)
        :hp(TPL_SOUL_ATTR.hp - 100)
        :mp(TPL_SOUL_ATTR.mp + 100)
        :move(TPL_SOUL_ATTR.move)
        :attack(TPL_SOUL_ATTR.attack + 60)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.3)
        :attackRange(TPL_SOUL_ATTR.attackRange + 500)
        :defend(TPL_SOUL_ATTR.defend - 10)
        :prop("sp", "MP恢复+3，冰体质|n光、钢抗性降低16%")
        :enchantMaterial(DAMAGE_TYPE.ice)
        :enchantResistance(DAMAGE_TYPE.light, -16)
        :enchantResistance(DAMAGE_TYPE.steel, -16),
    UnitTpl("FaerieDragon")
        :name("毒泠(怪萌)")
        :icon("unit/PoisonElemental")
        :modelAlias("hero/PoisonElemental")
        :modelScale(1.0)
        :scale(1.3)
        :material(UNIT_MATERIAL.flesh)
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("missile/SpiritBolt")
                                :damageType(DAMAGE_TYPE.poison)
                                :speed(700):height(30))
        :stature(65)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp)
        :mp(TPL_SOUL_ATTR.mp)
        :move(TPL_SOUL_ATTR.move - 5)
        :attack(TPL_SOUL_ATTR.attack + 5)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.2)
        :attackRange(TPL_SOUL_ATTR.attackRange + 300)
        :defend(TPL_SOUL_ATTR.defend - 3)
        :prop("sp", "毒免疫，毒体质|n岩、风抗性降低30%")
        :enchantImmune(DAMAGE_TYPE.poison, 1)
        :enchantMaterial(DAMAGE_TYPE.poison)
        :enchantResistance(DAMAGE_TYPE.rock, -30)
        :enchantResistance(DAMAGE_TYPE.wind, -30),
    UnitTpl("KelThuzadLich")
        :name("刍泠(噩法师)")
        :icon("unit/BoneHelmet")
        :modelAlias("hero/HeroDeposedWarlock")
        :modelScale(1.0)
        :scale(1.2)
        :material(UNIT_MATERIAL.flesh)
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("DemonHunterMissile")
                                :damageType(DAMAGE_TYPE.dark)
                                :speed(900):height(50))
        :stature(90)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen + 2)
        :hp(TPL_SOUL_ATTR.hp - 150)
        :mp(TPL_SOUL_ATTR.mp + 100)
        :move(TPL_SOUL_ATTR.move - 50)
        :attack(TPL_SOUL_ATTR.attack - 35)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.3)
        :attackRange(TPL_SOUL_ATTR.attackRange + 450)
        :defend(TPL_SOUL_ATTR.defend - 20)
        :prop("sp", "MP恢复+2，暗体质|n光抗性降低60%")
        :enchantMaterial(DAMAGE_TYPE.dark)
        :enchantResistance(DAMAGE_TYPE.light, -60),
    UnitTpl("HeroBladeMaster")
        :name("剑泠(阎殇)")
        :icon("unit/ChaosBlademaster")
        :castAnimation("attack slam")
        :keepAnimation("attack slam")
        :modelAlias("HeroChaosBladeMaster")
        :modelScale(1.0)
        :scale(1.2)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_slice_heavy")
        :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.fire))
        :stature(65)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 250)
        :mp(TPL_SOUL_ATTR.mp)
        :move(TPL_SOUL_ATTR.move)
        :attack(TPL_SOUL_ATTR.attack + 90)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.1)
        :attackRange(TPL_SOUL_ATTR.attackRange)
        :defend(TPL_SOUL_ATTR.defend + 2)
        :prop("sp", "10%几率暴击150%伤害|n火抗性提升25%，水抗性降低25%")
        :crit(50):odds("crit", 10)
        :enchantResistance(DAMAGE_TYPE.fire, 25)
        :enchantResistance(DAMAGE_TYPE.water, -25),
    UnitTpl("NagaMyrmidon")
        :name("汐泠(卫将)")
        :icon("unit/OverlordGreen")
        :modelAlias("hero/NagaDeathKnightFxd")
        :modelScale(1.0)
        :scale(1.4)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_chop_medium")
        :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.water))
        :stature(65)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 360)
        :mp(TPL_SOUL_ATTR.mp - 100)
        :move(TPL_SOUL_ATTR.move + 5)
        :attack(TPL_SOUL_ATTR.attack + 40)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.1)
        :attackRange(TPL_SOUL_ATTR.attackRange)
        :defend(TPL_SOUL_ATTR.defend + 3)
        :prop("sp", "两栖移动|n水抗性提升40%，雷抗性降低45%")
        :moveType(UNIT_MOVE_TYPE.amphibious)
        :enchantResistance(DAMAGE_TYPE.water, 40)
        :enchantResistance(DAMAGE_TYPE.thunder, -45),
    UnitTpl("Dryad")
        :name("花泠(小鹿)")
        :icon("unit/ForestDruid")
        :modelAlias("hero/FlowerDryad")
        :modelScale(1.0)
        :scale(1.4)
        :material(UNIT_MATERIAL.wood)
        :weaponLength(80)
        :weaponHeight(80)
        :attackMode(AttackMode():mode("missile")
                                :missileModel("missile/BlessingArrow")
                                :damageType(DAMAGE_TYPE.grass)
                                :speed(1200):height(50))
        :stature(80)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 80)
        :mp(TPL_SOUL_ATTR.mp + 50)
        :move(TPL_SOUL_ATTR.move + 15)
        :attack(TPL_SOUL_ATTR.attack - 20)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase)
        :attackRange(TPL_SOUL_ATTR.attackRange + 400)
        :defend(TPL_SOUL_ATTR.defend - 17)
        :prop("sp", "草体质，草强化35%|n火、风抗性降低25%")
        :enchantMaterial(DAMAGE_TYPE.grass)
        :enchant(DAMAGE_TYPE.grass, 35)
        :enchantResistance(DAMAGE_TYPE.fire, -25)
        :enchantResistance(DAMAGE_TYPE.wind, -25),
    UnitTpl("PandarenBrewmaster")
        :name("熊猫泠(醉仙)")
        :icon("unit/PandaBrewmaster")
        :castAnimation("spell slam")
        :keepAnimation("spell throw")
        :modelAlias("PandarenBrewmaster")
        :modelScale(1.1)
        :scale(1.5)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("wood_bash_heavy")
        :attackMode(AttackMode():mode("common"))
        :stature(65)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 160)
        :mp(TPL_SOUL_ATTR.mp + 300)
        :move(TPL_SOUL_ATTR.move - 30)
        :attack(TPL_SOUL_ATTR.attack + 30)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.7)
        :attackRange(TPL_SOUL_ATTR.attackRange + 50)
        :defend(TPL_SOUL_ATTR.defend + 8)
        :prop("sp", "9%几率击晕0.5秒|n暗、火抗性降低30%")
        :stun(0.5):odds("stun", 9)
        :enchantResistance(DAMAGE_TYPE.dark, -30)
        :enchantResistance(DAMAGE_TYPE.fire, -30),
    UnitTpl("HeroTaurenChieftain")
        :name("酋泠(牛头人)")
        :icon("unit/HeroTaurenChieftain")
        :modelAlias("HeroTaurenChieftain")
        :modelScale(1.2)
        :scale(1.7)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_chop_heavy")
        :attackMode(AttackMode():mode("common"))
        :stature(65)
        :hpRegen(TPL_SOUL_ATTR.hpRegen + 5)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 400)
        :mp(TPL_SOUL_ATTR.mp)
        :move(TPL_SOUL_ATTR.move)
        :attack(TPL_SOUL_ATTR.attack + 25)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.6)
        :attackRange(TPL_SOUL_ATTR.attackRange + 150)
        :defend(TPL_SOUL_ATTR.defend + 5)
        :prop("sp", "HP提升10%，HP恢复+5|n草抗性降低30%")
        :mutation("hp", 5)
        :enchantResistance(DAMAGE_TYPE.grass, -30),
    UnitTpl("DragonSpawn")
        :name("龙泠(青龙拳师)")
        :icon("unit/BlueDragonSpawn")
        :modelAlias("hero/AzureDragonJudicator")
        :modelScale(1.0)
        :scale(1.5)
        :material(UNIT_MATERIAL.flesh)
        :attackPoint(0.3)
        :weaponLength(130)
        :weaponHeight(100)
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("missile/Forst_arrow")
                                :damageType(DAMAGE_TYPE.ice)
                                :speed(1000):height(0))
        :stature(70)
        :hpRegen(TPL_SOUL_ATTR.hpRegen + 7)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 220)
        :mp(TPL_SOUL_ATTR.mp + 40)
        :move(TPL_SOUL_ATTR.move - 10)
        :attack(TPL_SOUL_ATTR.attack + 50)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.3)
        :attackRange(TPL_SOUL_ATTR.attackRange + 300)
        :defend(TPL_SOUL_ATTR.defend + 3)
        :prop("sp", "HP恢复+6|n冰、光抗性提升20%，岩抗性降低40%")
        :enchantResistance(DAMAGE_TYPE.ice, 20)
        :enchantResistance(DAMAGE_TYPE.light, 20)
        :enchantResistance(DAMAGE_TYPE.rock, -40),
    UnitTpl("Revenant")
        :name("死泠(镰刀)")
        :icon("unit/HiddenApostle")
        :modelAlias("hero/wight")
        :modelScale(0.9)
        :scale(1.4)
        :material(UNIT_MATERIAL.flesh)
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("missile/CarrionBatBlood")
                                :damageType(DAMAGE_TYPE.dark)
                                :speed(1000):height(0))
        :stature(90)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp)
        :mp(TPL_SOUL_ATTR.mp + 70)
        :move(TPL_SOUL_ATTR.move - 45)
        :attack(TPL_SOUL_ATTR.attack + 65)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.2)
        :attackRange(TPL_SOUL_ATTR.attackRange + 250)
        :defend(TPL_SOUL_ATTR.defend)
        :prop("sp", "暗、光抗性90%|n雷抗性降低85%")
        :enchantResistance(DAMAGE_TYPE.dark, 90)
        :enchantResistance(DAMAGE_TYPE.light, 90)
        :enchantResistance(DAMAGE_TYPE.thunder, -85),
    UnitTpl("Medivh")
        :name("旅泠(方长)")
        :icon("unit/Medivh")
        :modelAlias("hero/Necromancer")
        :modelScale(1.0)
        :scale(1.2)
        :material(UNIT_MATERIAL.flesh)
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("missile/Shot_II_Green")
                                :damageType(DAMAGE_TYPE.light)
                                :speed(750):height(0))
        :stature(70)
        :hpRegen(TPL_SOUL_ATTR.hpRegen + 4)
        :mpRegen(TPL_SOUL_ATTR.mpRegen + 4)
        :hp(TPL_SOUL_ATTR.hp - 170)
        :mp(TPL_SOUL_ATTR.mp + 140)
        :move(TPL_SOUL_ATTR.move - 15)
        :attack(TPL_SOUL_ATTR.attack + 55)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.2)
        :attackRange(TPL_SOUL_ATTR.attackRange + 250)
        :defend(TPL_SOUL_ATTR.defend)
        :prop("sp", "HP/MP恢复+4|n草、毒抗性提升15%，风抗性降低25%")
        :enchantResistance(DAMAGE_TYPE.grass, 15)
        :enchantResistance(DAMAGE_TYPE.poison, 15)
        :enchantResistance(DAMAGE_TYPE.wind, -25),
    UnitTpl("ObsidianDestroyer")
        :name("耀泠(阿卡玛)")
        :icon("unit/Akama")
        :modelAlias("hero/VindicatorLostOneV1.02")
        :modelScale(1.0)
        :scale(1.1)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_bash_medium")
        :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.light))
        :stature(50)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 200)
        :mp(TPL_SOUL_ATTR.mp + 200)
        :move(TPL_SOUL_ATTR.move)
        :attack(TPL_SOUL_ATTR.attack + 33)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.1)
        :attackRange(TPL_SOUL_ATTR.attackRange + 55)
        :defend(TPL_SOUL_ATTR.defend + 12)
        :prop("sp", "3%几率击晕2秒|n光强化40%，钢抗性降低20%")
        :stun(2):odds("stun", 3)
        :enchant(DAMAGE_TYPE.light, 40)
        :enchantResistance(DAMAGE_TYPE.steel, -20),
    UnitTpl("WolfRider")
        :name("剑泠(缠水)")
        :icon("unit/Voljin2")
        :castAnimation("attack slam")
        :keepAnimation("attack slam")
        :modelAlias("hero/BladeMasterJungleTrollV1.01")
        :modelScale(1.0)
        :scale(1.1)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_slice_light")
        :attackMode(AttackMode():mode("common"))
        :stature(65)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 140)
        :mp(TPL_SOUL_ATTR.mp + 100)
        :move(TPL_SOUL_ATTR.move - 35)
        :attack(TPL_SOUL_ATTR.attack + 50)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase)
        :attackRange(TPL_SOUL_ATTR.attackRange)
        :defend(TPL_SOUL_ATTR.defend - 1)
        :prop("sp", "水强化55%，冰抗性降低30%")
        :enchant(DAMAGE_TYPE.water, 55)
        :enchantResistance(DAMAGE_TYPE.ice, -30),
    UnitTpl("Sorceress")
        :name("枪泠(电弧鼠)")
        :icon("war3mapImports\\ElectricMouse.tga")
        :modelAlias("war3mapImports\\ElectricMouse.mdl")
        :modelScale(1.0)
        :scale(1.1)
        :material(UNIT_MATERIAL.flesh)
        :weaponSoundMode(2)
        :weaponSound("cannon_hit_heavy")
        :weaponLength(130)
        :weaponHeight(15)
        :attackPoint(0.2)
        :attackMode(AttackMode():mode("missile")
                                :missileModel("war3mapImports\\ElectricMouseMissile.mdl")
                                :damageType(DAMAGE_TYPE.thunder)
                                :speed(1500):height(0))
        :stature(70)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 50)
        :mp(TPL_SOUL_ATTR.mp + 50)
        :move(TPL_SOUL_ATTR.move - 20)
        :attack(TPL_SOUL_ATTR.attack + 70)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.2)
        :attackRange(TPL_SOUL_ATTR.attackRange + 300)
        :defend(TPL_SOUL_ATTR.defend + 6)
        :prop("sp", "雷强化15%|n雷抗性提升15%，岩抗性降低30%")
        :enchant(DAMAGE_TYPE.thunder, 15)
        :enchantResistance(DAMAGE_TYPE.thunder, 15)
        :enchantResistance(DAMAGE_TYPE.rock, -30),
    UnitTpl("DarkRanger")
        :name("夜泠(游侠)")
        :icon("unit/DarkRangerDegenerate")
        :modelAlias("hero/TheBansheeQueen")
        :modelScale(1.0)
        :scale(1.1)
        :material(UNIT_MATERIAL.flesh)
        :attackMode(AttackMode():mode("missile"):gatlin(1)
                                :missileModel("BlackArrowMissile")
                                :damageType(DAMAGE_TYPE.dark)
                                :speed(1400):height(50))
        :stature(50)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp - 300)
        :mp(TPL_SOUL_ATTR.mp - 130)
        :move(TPL_SOUL_ATTR.move + 30)
        :attack(TPL_SOUL_ATTR.attack + 40)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.3)
        :attackRange(TPL_SOUL_ATTR.attackRange + 450)
        :defend(TPL_SOUL_ATTR.defend - 9)
        :prop("sp", "攻击额外多1支箭，光抗性降低20%")
        :enchantResistance(DAMAGE_TYPE.light, -20),
    UnitTpl("EvilIllidan")
        :name("魔泠(恶魔猎手)")
        :icon("unit/EvilIllidan")
        :keepAnimation("stand channel")
        :modelAlias("EvilIllidan")
        :modelScale(1.0)
        :scale(1.2)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_slice_light")
        :weaponHeight(55)
        :attackMode(AttackMode():mode("missile")
                                :missileModel("slash/Animeslashfinal")
                                :speed(1500):height(0))
        :stature(55)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp - 500)
        :mp(TPL_SOUL_ATTR.mp - 50)
        :move(TPL_SOUL_ATTR.move + 20)
        :attack(TPL_SOUL_ATTR.attack + 15)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.2)
        :attackRange(TPL_SOUL_ATTR.attackRange + 50)
        :defend(TPL_SOUL_ATTR.defend - 3)
        :prop("sp", "攻速提升15%、命中提升22%|n火、雷抗性降低25%")
        :attackSpeed(15)
        :aim(22)
        :enchantResistance(DAMAGE_TYPE.fire, -25)
        :enchantResistance(DAMAGE_TYPE.thunder, -25),
    UnitTpl("PitLord")
        :name("剑泠(黑月)")
        :icon("unit/Guldan2")
        :castAnimation("attack slam")
        :keepAnimation("attack slam")
        :modelAlias("hero/UjimasaHojoV1.07")
        :modelScale(1.0)
        :scale(1.1)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_slice_heavy")
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("OrbOfDeathMissile")
                                :speed(1300):height(0)
                                :damageType(DAMAGE_TYPE.dark))
        :stature(40)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 260)
        :mp(TPL_SOUL_ATTR.mp + 50)
        :move(TPL_SOUL_ATTR.move)
        :attack(TPL_SOUL_ATTR.attack - 50)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.4)
        :attackRange(TPL_SOUL_ATTR.attackRange + 200)
        :defend(TPL_SOUL_ATTR.defend)
        :prop("sp", "暗强化50%，光抗性降低50%")
        :enchant(DAMAGE_TYPE.dark, 50)
        :enchantResistance(DAMAGE_TYPE.light, -50),
    UnitTpl("Unbroken")
        :name("离子泠(电子)")
        :icon("unit/IcyGhostA")
        :modelAlias("hero/NakedLightning")
        :modelScale(1.0)
        :scale(1.2)
        :material(UNIT_MATERIAL.flesh)
        :attackMode(AttackMode():mode("lightning")
                                :lightningType(LIGHTNING_TYPE.thunderShot):reflex(2)
                                :damageType(DAMAGE_TYPE.thunder):damageTypeLevel(2))
        :stature(55)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp - 50)
        :mp(TPL_SOUL_ATTR.mp - 175)
        :move(TPL_SOUL_ATTR.move + 30)
        :attack(TPL_SOUL_ATTR.attack - 40)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase)
        :attackRange(TPL_SOUL_ATTR.attackRange + 500)
        :defend(TPL_SOUL_ATTR.defend)
        :prop("sp", "攻击会反射2次，雷免疫，雷体质|n岩抗性降低20%")
        :enchantImmune(DAMAGE_TYPE.thunder, 1)
        :enchantMaterial(DAMAGE_TYPE.thunder)
        :enchantResistance(DAMAGE_TYPE.rock, -20),
    UnitTpl("Skeleton")
        :name("骷髅泠(骨王)")
        :icon("unit/SkeletalDeathKnightHero")
        :modelAlias("hero/Skeleton_Death_Knight")
        :modelScale(1.0)
        :scale(1.2)
        :material(UNIT_MATERIAL.metal)
        :weaponSound("metal_chop_medium")
        :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.steel))
        :stature(80)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 280)
        :mp(TPL_SOUL_ATTR.mp - 115)
        :move(TPL_SOUL_ATTR.move - 45)
        :attack(TPL_SOUL_ATTR.attack + 110)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.5)
        :attackRange(TPL_SOUL_ATTR.attackRange + 100)
        :defend(TPL_SOUL_ATTR.defend + 7)
        :prop("sp", "HP提升10%，减伤10%|n岩、火抗性提升25%，钢抗性降低33%")
        :mutation("hp", 10)
        :hurtReduction(10)
        :enchantResistance(DAMAGE_TYPE.rock, 25)
        :enchantResistance(DAMAGE_TYPE.fire, 25)
        :enchantResistance(DAMAGE_TYPE.rock, -33),
    UnitTpl("HeroFireLord")
        :name("焰泠(鬼火灵)")
        :icon("unit/HellstoneGolem")
        :modelAlias("HeroFlameLord")
        :modelScale(1.0)
        :scale(1.2)
        :material(UNIT_MATERIAL.flesh)
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("LordofFlameMissile")
                                :damageType(DAMAGE_TYPE.fire)
                                :speed(800):height(0))
        :stature(65)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp - 330)
        :mp(TPL_SOUL_ATTR.mp + 180)
        :move(TPL_SOUL_ATTR.move + 20)
        :attack(TPL_SOUL_ATTR.attack)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.1)
        :attackRange(TPL_SOUL_ATTR.attackRange + 400)
        :defend(TPL_SOUL_ATTR.defend - 6)
        :prop("sp", "火体质，火抗性提升75%，冰抗性降低35%")
        :enchantMaterial(DAMAGE_TYPE.fire)
        :enchantResistance(DAMAGE_TYPE.fire, 75)
        :enchantResistance(DAMAGE_TYPE.ice, -35),
    UnitTpl("NagaRoyalGuard")
        :name("海皇泠(鲨煌)")
        :icon("unit/BronzeDragonSpawn")
        :modelAlias("hero/NagaRoyalGuard_V2")
        :modelScale(1.0)
        :scale(1.4)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_chop_heavy")
        :attackMode(AttackMode():mode("common"):damageType(DAMAGE_TYPE.water))
        :stature(70)
        :hpRegen(TPL_SOUL_ATTR.hpRegen + 8)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 370)
        :mp(TPL_SOUL_ATTR.mp - 30)
        :move(TPL_SOUL_ATTR.move + 25)
        :attack(TPL_SOUL_ATTR.attack + 50)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.4)
        :attackRange(TPL_SOUL_ATTR.attackRange + 50)
        :defend(TPL_SOUL_ATTR.defend + 10)
        :prop("sp", "两栖移动|nHP恢复+8，防御提升5%|n水、风抗性提升25%，草、雷抗性降低25%")
        :mutation("defend", 5)
        :moveType(UNIT_MOVE_TYPE.amphibious)
        :enchantResistance(DAMAGE_TYPE.water, 25)
        :enchantResistance(DAMAGE_TYPE.wind, 25)
        :enchantResistance(DAMAGE_TYPE.grass, -25)
        :enchantResistance(DAMAGE_TYPE.thunder, -25),
    UnitTpl("KelThuzadLich")
        :name("灭泠(巨鹿魔)")
        :icon("unit/AchievementEmeraldnightmareCenarius")
        :modelAlias("hero/Cenarius_Nightmare")
        :modelScale(1.0)
        :scale(1.8)
        :material(UNIT_MATERIAL.flesh)
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("missile/DarknessBomb")
                                :scatter(5):radius(600)
                                :damageType(DAMAGE_TYPE.dark)
                                :speed(1200):height(400))
        :stature(80)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp - 250)
        :mp(TPL_SOUL_ATTR.mp + 230)
        :move(TPL_SOUL_ATTR.move)
        :attack(TPL_SOUL_ATTR.attack + 10)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 1.1)
        :attackRange(TPL_SOUL_ATTR.attackRange + 575)
        :defend(TPL_SOUL_ATTR.defend)
        :prop("sp", "光抗性提升100%|n毒抗性降低100%")
        :enchantResistance(DAMAGE_TYPE.light, 100)
        :enchantResistance(DAMAGE_TYPE.poison, -100),
    UnitTpl("Wendigo")
        :name("祭泠(弋洛伽)")
        :icon("unit/Eligor")
        :modelAlias("hero/Eligoropt")
        :modelScale(1.0)
        :scale(1.3)
        :material(UNIT_MATERIAL.flesh)
        :weaponSound("metal_chop_heavy")
        :attackMode(AttackMode():mode("missile")
                                :missileModel("eff/ShockWave")
                                :damageType(DAMAGE_TYPE.wind)
                                :speed(2000):height(0))
        :stature(70)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 160)
        :mp(TPL_SOUL_ATTR.mp - 70)
        :move(TPL_SOUL_ATTR.move + 25)
        :attack(TPL_SOUL_ATTR.attack + 33)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase - 0.3)
        :attackRange(TPL_SOUL_ATTR.attackRange + 200)
        :defend(TPL_SOUL_ATTR.defend + 9)
        :prop("sp", "攻击浮动80|n结算攻速提升5%|n毒抗性提升33%，钢、风抗性降低25%")
        :attackRipple(80)
        :mutation("attackSpeed", 5)
        :enchantResistance(DAMAGE_TYPE.poison, 33)
        :enchantResistance(DAMAGE_TYPE.steel, -25)
        :enchantResistance(DAMAGE_TYPE.wind, -25),
    UnitTpl("abomination")
        :name("沙泠(法老尸)")
        :icon("unit/RevenantOfTheDepths")
        :modelAlias("hero/EarthLich")
        :modelScale(1.0)
        :scale(1.4)
        :material(UNIT_MATERIAL.flesh)
        :weaponLength(100)
        :weaponHeight(0)
        :attackMode(AttackMode():mode("missile"):homing(true)
                                :missileModel("missile/ThornMissile")
                                :damageType(DAMAGE_TYPE.rock)
                                :speed(600):height(0))
        :stature(80)
        :hpRegen(TPL_SOUL_ATTR.hpRegen)
        :mpRegen(TPL_SOUL_ATTR.mpRegen)
        :hp(TPL_SOUL_ATTR.hp + 90)
        :mp(TPL_SOUL_ATTR.mp + 180)
        :move(TPL_SOUL_ATTR.move - 55)
        :attack(TPL_SOUL_ATTR.attack)
        :attackSpaceBase(TPL_SOUL_ATTR.attackSpaceBase + 0.4)
        :attackRange(TPL_SOUL_ATTR.attackRange + 500)
        :defend(TPL_SOUL_ATTR.defend + 3)
        :prop("sp", "岩体质，回避提升10%|n火抗性提升50%，草、水抗性降低50%")
        :avoid(10)
        :enchantMaterial(DAMAGE_TYPE.rock)
        :enchantResistance(DAMAGE_TYPE.fire, 50)
        :enchantResistance(DAMAGE_TYPE.grass, -50)
        :enchantResistance(DAMAGE_TYPE.water, -50),
}
local s = Store("soul")
s:name("英泠伙伴")
s:description(function(this)
    return {
        this:name() .. "(" .. colour.hex(colour.gold, "O") .. ")",
        "纪录在这里",
        "可随时解封"
    }
end)
local c = s:salesGoods():count()
for i = 1, #TPL_SOUL, 1 do
    local v = TPL_SOUL[i]
    v:prop("idx", i)
    v:entertain(BIOGRAPHIES[v:name()])
    v:barStateAlways(true)
     :barStateMode(1)
     :barStateMarker(1000)
     :iconMap(AUIKit("ninegrids_minimap", "dot/boss", "tga"), 0.04, 0.04)
    if (i > 8) then
        v:condition(function() return Game():soul(i) == true end)
         :conditionTips("打败：" .. TPL_SOUL[i]:name())
    end
    if (i > c) then
        s:insert(v)
    end
end